INSERT INTO AUTUACAO.PROCESSO(SEQ_PROCESSO, SEQ_PROTOCOLO, SIG_CLASSE, TIP_STATUS, NUM_PROCESSO, SIG_AUTUADOR, DAT_AUTUACAO, QTD_RECURSO, TIP_MEIO_TRAMITACAO, TIP_SIGILO, FLG_PROCESSO_APTO, TXT_ANALISE_PRESSUPOSTO_FORMAL, TXT_ANALISE_REPERCUSSAO_GERAL, TIP_PROCESSO) VALUES
(9014, 9002, 'RE', 'AUTUADO', '100', 'autuador', SYSDATE, 1, 'ELETRONICO', 'PUBLICO', 'Y', 'Processo apto.', NULL, 'RECURSAL');              

INSERT INTO AUTUACAO.PROCESSO_TESE (SEQ_PROCESSO, SEQ_TESE) VALUES
(9014, 1001);

INSERT INTO AUTUACAO.PROCESSO_ASSUNTO (SEQ_PROCESSO, COD_ASSUNTO) VALUES
(9014, '4355');

INSERT INTO AUTUACAO.PARTE(SEQ_PARTE, SEQ_PROCESSO, NOM_APRESENTACAO, TIP_POLO) VALUES
(9002, 9014, 'MARIA JOSÉ', 'ATIVO');

INSERT INTO AUTUACAO.PARTE(SEQ_PARTE, SEQ_PROCESSO, NOM_APRESENTACAO, TIP_POLO) VALUES
(9003, 9014, 'ANTÔNIO DE PAULA', 'PASSIVO');