INSERT INTO AUTUACAO.PROCESSO(SEQ_PROCESSO, SEQ_PROTOCOLO, SIG_CLASSE, TIP_STATUS, NUM_PROCESSO, SIG_AUTUADOR, DAT_AUTUACAO, QTD_RECURSO, TIP_MEIO_TRAMITACAO, TIP_SIGILO, FLG_PROCESSO_APTO, TXT_ANALISE_PRESSUPOSTO_FORMAL, TXT_ANALISE_REPERCUSSAO_GERAL, TIP_PROCESSO) VALUES
(9004, 9002, 'ADI', 'AUTUADO', '100', 'autuador', SYSDATE, 1, 'ELETRONICO', 'PUBLICO', 'Y', NULL, NULL, 'ORIGINARIO');              

INSERT INTO AUTUACAO.PARTE(SEQ_PARTE, SEQ_PROCESSO, NOM_APRESENTACAO, TIP_POLO) VALUES
(9000, 9004, 'JOSE SILVA', 'ATIVO');

INSERT INTO AUTUACAO.PARTE(SEQ_PARTE, SEQ_PROCESSO, NOM_APRESENTACAO, TIP_POLO) VALUES
(9001, 9004, 'MARIA PAULA', 'PASSIVO');