DELETE AUTUACAO.PROCESSO_TESE WHERE SEQ_PROCESSO = 9014;

DELETE AUTUACAO.PROCESSO_ASSUNTO WHERE SEQ_PROCESSO = 9014;

DELETE AUTUACAO.PARTE WHERE SEQ_PROCESSO = 9014;              

DELETE AUTUACAO.PROCESSO WHERE SEQ_PROCESSO = 9014;              