sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
addons:
  hosts:
  - docker
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- docker save -o $HOME/docker_cache/docker.tar stfdigital-autuacao-autuacao $(docker history -q stfdigital-autuacao-autuacao | tail -n +2 | grep -v \<missing\> | tr '\n' ' ')
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - node_cache
  - node_modules
  - "$HOME/docker_cache"
before_install:
- "./scripts/upgrade-docker.sh"
- mkdir -p $HOME/docker_cache
install: docker load -i $HOME/docker_cache/docker.tar || true
script: gradle docker && gradle gulpTestUnit && ./scripts/test-e2e.sh
notifications:
  slack:
    secure: KBOtc59Yck1JDT/nJdTgF+i5/PdZU3rGtwlkOVN1Mg4BSiprHApsj7UjPJcDzfeqHAAgybAOtRDZwN4R7WlCioEkxCV7x4omaaAstG9mXlkCGDcKiyvyWKLp5MPjNF8785J9IT/Kh4e2TsrTfD+Wo/xE8CrWRNIM67ylLTlylAIZYd+qQHY62hcQ6OxFjBaGGehgNBlsj15axUL+9Kt73gNaSjVgJ+V51nI83NmgnKY0ET4T9R/hgMda/+qLvvR+WeFR4Rv7CZ7alJXUEo3bGkTD/CFwXNN514knXv5WQujsskMmpgYnNa73SzolzOypAY1Xx00YSfEt5czBDrmt/+E4CeYIQxDwEV9mWw7ToAGdkUfGDYTpFEd8ppWk0P9XHeoor4RB+USSbnpLPxe+zT7nqEwCuYFGYkpOk3rNHiZDqLCDw6XQGi+oEXW2W54q6sg8zwFkJtVLadwdI/vSu3HPFC+D6AZBg/1gBq6rfUORnhtoTuvhF030dlVPbNwGuOXwZMJkK4GSAvTM85pvlic9kGU4PvwkHNUZ9h51naelXoLY1AQvc9hKVdKprIV31Kt2IScoAdOvqarOilx1uE44awkwUYDiXbcjK8HvzK8oHcgbClA0q4FsbthoHh6DvoTVeYPZkQTTBAjohnJXpVECfWemrlWcgzqgnBTUWW4=
