# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  autuacao:
    extends:
      file: compose/shared/common.yml
      service: autuacao
    depends_on:
     - rabbit
     - discovery